### ISSUE TITLE
CRSWKT.activeExtension() checks for extension_name 'gpkg_crs_wkt'

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ets-gpkg12#10]
There's this test SELECT count(*) from gpkg_extensions WHERE extension_name = 'gpkg_crs_wkt' in https://github.com/opengeospatial/ets-gpkg12/blob/5d5f7125846f94832f96064f1fcd0c72299a1ce8/src/main/java/org/opengis/cite/gpkg12/extensions/crswkt/CRSWKT.java#L41 but there is no requirement in the spec for the extension to be registered that way

**Comment by jyutzler** [comment]
We added this requirement (since an app would have no way of knowing about it otherwise without duck-typing).
