### ISSUE TITLE
Test method featureGeometryEncodingTesting fail on null geometries

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ets-gpkg12#106]
The attached log [s0022.zip](https://github.com/opengeospatial/ets-gpkg12/files/5011910/s0022.zip) of the GeoPackage 1.2 test suite on https://cite.opengeospatial.org/te2/  shows that feature tables that contain NULL geometries (reproducer file new_geopackage.gpkg is included in the zip) cause the following failure:
```
Test method featureGeometryEncodingTesting: 
              Failure in test process while processing feature geometry column blob entry for main loop; error message: No geom available..
```

This failure is likely a false positive (due to comment "// We must allow for null geometries"). It looks like it might be a side-effect of this commit https://github.com/opengeospatial/ets-gpkg12/commit/ab9eb29c9c107d9540fbfef137c29d00badc92c1

**Comment by dstenger** [comment]
Thank you for reporting. We will take a look at the reported behavior.

**Comment by keshavnangare** [comment]
@dstenger 

The changes are fine and tested successfully on local environment.

**Comment by keshavnangare** [comment]
@dstenger 

I have taken the latest pull and tested the changes on local environment successfully.
