### ISSUE TITLE
Relocate "commons-io" in pom

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/ets-gpkg12#107]
We need to update our pom.xml

[INFO] Reading assembly descriptor: /Users/JeffYutzler/projects/ets-gpkg12/src/assembly/aio.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar (88 kB at 316 kB/s)
[WARNING] While downloading org.apache.commons:commons-io:1.3.2
  This artifact has been relocated to commons-io:commons-io:1.3.2.
  https://issues.sonatype.org/browse/MVNCENTRAL-244

**Comment by keshavnangare** [comment]
@dstenger 

We are good with changes and tested successfully on local environment.
