### ISSUE TITLE
WEBP test sems to accept PNG or JPEG tiles as well

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ets-gpkg12#11]
My understanding of https://github.com/opengeospatial/ets-gpkg12/blob/master/src/main/java/org/opengis/cite/gpkg12/extensions/webp/WebPTests.java#L163 is that it will accept WEBP tiles as soon as the extension is declared.

But my understanding of http://www.geopackage.org/spec/#92 is that a webp enabled tile pyramid user table should contain only webp tiles ("""The MIME type of values of the tile_data column in tile pyramid user data tables SHALL be image/x-webp."""). I'm wondering if the intent of requirement 92 was really to exclude png and jpeg tiles in which case the test is OK but the requirement should be rewritten

**Comment by jyutzler** [comment]
We have fixed the wording on the requirement.
