### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#118]
When master branch is built with following command `mvn clean verify -Pintegration-tests`, the integration tests are failing.

**Comment by dstenger** [comment]
@keshav-nangare Can you please check why one test less is passed than before (see https://github.com/opengeospatial/ets-gpkg12/pull/119/files)? What pull request did break the integration tests (probably one of those https://github.com/opengeospatial/ets-gpkg12/milestone/8?closed=1)?

**Comment by keshavnangare** [comment]
@dstenger 

I checked that one test passed less than earlier because of the removal of `featureSRSconsistency` test in the https://github.com/opengeospatial/ets-gpkg12/pull/110/commits/516f2bb1a3e1c273b5440f758127bc5bb6a4c004.
