### ISSUE TITLE
Column Data Types - Invalid data type for TEXT column

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/ets-gpkg12#128]
Hi,

CITE reports FAIL on "column Data Types".

I have used TEXT columns in my GPKG with declaration of `maxchar_count`.
According to [1.2.1 version](https://www.geopackage.org/spec121/index.html#table_column_data_types) of standard and [current version 1.4](https://www.geopackage.org/spec/#table_column_data_types) this should be allowed as described in **Table 1**.

The same table is referenced in [CITE documentation](https://opengeospatial.github.io/ets-gpkg12/apidocs/org/opengis/cite/gpkg12/core/DataContentsTests.html#columnDataTypes--) for this test.

![table1_gpkg](https://github.com/opengeospatial/ets-gpkg12/assets/1849293/cad15687-bc0c-4eb2-b48c-b9267206fd0e)

This should be eventually a warning for this case in my opinion if there is such status.

I am not aware if this topic was discussed before, if there is an agreement on this, please close bug report.

**Comment by dstenger** [comment]
Thank you for reporting.
Do you have a test file which we can use to reproduce the error? If not, can you please document the exact error message?

**Comment by phidrho** [comment]
@dstenger
I prepared an test file which causes Fail on `Core` > `column Data Types` with `Reason`:

`Invalid data type: TEXT (500) for column text_data_limited in table my_attribute_table`

[Maxchar Count Bug example](https://github.com/opengeospatial/ets-gpkg12/files/15187062/limited_text_example.zip)

**Comment by bpross-52n** [comment]
@phidrho The test suite takes the `maxchar_count` into account, but it is checked against a regular expression. See [here](https://github.com/opengeospatial/ets-gpkg12/blob/04b4a0b8c7d90755b016182e2992684f198da1ba/src/main/java/org/opengis/cite/gpkg12/core/DataContentsTests.java#L267) However, this check does not expect a blank between TEXT and the opening bracket. Would it be possible for you to remove the blank in the datatype description, i.e. `TEXT(500)`?

**Comment by jyutzler** [comment]
> @phidrho The test suite takes the `maxchar_count` into account, but it is checked against a regular expression. See [here](https://github.com/opengeospatial/ets-gpkg12/blob/04b4a0b8c7d90755b016182e2992684f198da1ba/src/main/java/org/opengis/cite/gpkg12/core/DataContentsTests.java#L267) However, this check does not expect a blank between TEXT and the opening bracket. Would it be possible for you to remove the blank in the datatype description, i.e. `TEXT(500)`?

Wouldn't it make sense to adjust the regular expression instead?

**Comment by dstenger** [comment]
Sure, this might also be an option.
We could truncate all white spaces. However, it has to be checked if this is compliant to the specification.

**Comment by jyutzler** [comment]
> Sure, this might also be an option. We could truncate all white spaces. However, it has to be checked if this is compliant to the specification.

Yes, it is compliant to the specification. Thanks to [datatype affinity](https://www.sqlite.org/datatype3.html) (according to them it is a feature not a bug), the underlying engine doesn't even care about those particulars. Therefore, we should lean towards permissiveness.

I would entertain a corrigendum to modify the relevant part of the [abstract test suite](https://www.geopackage.org/spec/#_data_19), if you think that is necessary.

**Comment by phidrho** [comment]
> @phidrho The test suite takes the `maxchar_count` into account, but it is checked against a regular expression. See [here](https://github.com/opengeospatial/ets-gpkg12/blob/04b4a0b8c7d90755b016182e2992684f198da1ba/src/main/java/org/opengis/cite/gpkg12/core/DataContentsTests.java#L267) However, this check does not expect a blank between TEXT and the opening bracket. Would it be possible for you to remove the blank in the datatype description, i.e. `TEXT(500)`?

It's not problem for me, now that I'm aware of it, but there are lots of automatic SQL formatters that might cause this. And I believe that it's allowed by SQL standard, because I never had trouble writing sintax this way, and I've used many different softwares for SQLite.
