### ISSUE TITLE
Data Columns Column Name test has wrong table name in description

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/ets-gpkg12#129]
Hi,

I got an FAIL result under [Schema > Data Columns Column Name](https://opengeospatial.github.io/ets-gpkg12/apidocs/org/opengis/cite/gpkg12/extensions/schema/SchemaTests.html#dataColumnsColumnName--).

Test is OK, everything works fine, but there is a minor bug in description under `Reason For Test Failure`, current test generates wrong explanation with `gpkg_extensions`:
"The gpkg_extensions table references column COLUMN_NAME which does not exist in table TABLE_NAME."

but should be with `gpkg_data_columns`:
"The gpkg_data_columns table references column COLUMN_NAME which does not exist in table TABLE_NAME."

**Comment by dstenger** [comment]
Thank you for reporting.
We will check and update the failure message.
