### ISSUE TITLE
Consistency in documentation and UI about what conformance classes are available 

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg12#15]
We need to update the index.html page and the CTL to provide information about the correct conformance classes. They are not consistent.

<img width="631" alt="gpk12" src="https://user-images.githubusercontent.com/3738898/29185453-45d135a2-7dd7-11e7-8d48-1bc39dc0e0ee.png">

And: http://cite.opengeospatial.org/te2/about/gpkg12/1.2/site/

<img width="1036" alt="gpk12scope" src="https://user-images.githubusercontent.com/3738898/29185564-9cd9baea-7dd7-11e7-9328-879f826af19c.png">
<img width="878" alt="gpk12-list-classes" src="https://user-images.githubusercontent.com/3738898/29185566-9f62ae7a-7dd7-11e7-82fd-8c00512038d7.png">

**Comment by bermud** [comment]
@dstenger, please review this test suite for consistency. We need to be sure that the index file is consistent with the user interface in terms of advertising the conformance classes. Also need to correct the name (1.0 to 1.2) and make a note that it is backwards compatible (I think).

**Comment by bermud** [comment]
@jyutzler @dstenger I'm still unsure about what is the scope of the test and what needs to be done. Can you please confirm and update the documentation as well as the welcome page that appears when executing the test. Thank you very much!

**Comment by dstenger** [comment]
Working branch: https://github.com/lat-lon/ets-gpkg12/tree/updateDocumentationAndUi-15

**Comment by dstenger** [comment]
Update start UI of Web Browser Interface: https://github.com/lat-lon/ets-gpkg12/commit/bcb8fee474fad46fa25fa8eff1d8c286e7421f5a
Set all GeoPackage version descriptions to 1.2: https://github.com/lat-lon/ets-gpkg12/commit/d4aef26bd6d90101dd30a29a6ee3822b1498ef99
Update site: https://github.com/lat-lon/ets-gpkg12/commit/f6d9e411d771bedcc5fbef53694875c54983a4b9
Update apidocs: https://github.com/lat-lon/ets-gpkg12/commit/c34791d946647096a23a9384e2a2e167d245ba08

**Comment by dstenger** [comment]
![gpkg12-ui](https://user-images.githubusercontent.com/2989166/31450845-cec9758c-aeaa-11e7-9ea1-1cb9ffb62e1b.png)

**Comment by dstenger** [comment]
@bermud @jyutzler 
I uploaded a screenshot of the current status of start UI of Web Browser Interface.
Do you have any questions or comments?

**Comment by jyutzler** [comment]
This looks okay to me. Is there a place where we can see it in action?

**Comment by dstenger** [comment]
Thank you for confirmation!

We will install it on beta environment when following bug is solved: #17

**Comment by dstenger** [comment]
Pull request was created: #18
