### ISSUE TITLE
All tests are skipped if official test data are used

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#16]
I tried to validate official test data from http://www.geopackage.org/#sampledata via Web Browser Interface.

However, there are always all tests skipped.

For example, I used following data:
* http://www.geopackage.org/data/gdal_sample_v1.2_no_extensions.gpkg
* http://www.geopackage.org/data/sample1_2.gpkg

**Comment by dstenger** [comment]
@jyutzler Can you please provide data which are passing the test suite? Do you know why all tests are skipped if official test data are used?

**Comment by jyutzler** [comment]
@dstenger If all tests are being skipped, then the test suite is not running on an actual GeoPackage. This means that something is mechanically wrong with the test suite - the intended test file is not being read. 

The functions in this class file are called during the unit test process. You can see all of the GeoPackages that are validated. It includes files that pass all tests (0 as the second parameter) and those that do not.
https://github.com/opengeospatial/ets-gpkg12/blob/master/src/test/java/org/opengis/cite/gpkg12/VerifyTestNGController.java

**Comment by dstenger** [comment]
The required conformance classes were not defined by web UI leading to execution of zero conformance classes.

Fixed with commit: https://github.com/lat-lon/ets-gpkg12/commit/d385ee0c7607e9716635368e7b97035cd0b40db5

Now, the examples from above can be validated with this test suite.
