### ISSUE TITLE
Review list of implemented conformance classes in test report and documentation

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#37]

**Comment by lgoltz** [comment]
Configured CCs:
https://github.com/opengeospatial/ets-gpkg12/blob/27084850e436846e6811f363ce76db44d549aa8d/src/main/config/teamengine/config.xml#L15-L28

Tests configured in testng.xml
https://github.com/opengeospatial/ets-gpkg12/blob/27084850e436846e6811f363ce76db44d549aa8d/src/main/resources/org/opengis/cite/gpkg12/testng.xml#L13-L75

Documentation (site): https://github.com/opengeospatial/ets-gpkg12/blob/master/src/site/markdown/index.md

**Comment by lgoltz** [comment]
The configuration in the config.xml contains all test configured in the testng.xml. 

It seems that the documentation is outdated, the CC  `Attributes` should be marked as implemented.

**Comment by lgoltz** [comment]
From http://www.geopackage.org/spec120/#_core and http://www.geopackage.org/spec120/#_options I understand that only the conformance class `Core` is mandatory. I think all other conformance classes should be removed from https://github.com/opengeospatial/ets-gpkg12/blob/27084850e436846e6811f363ce76db44d549aa8d/src/main/config/teamengine/config.xml as  `Core` is the basic conformance class.

**Comment by lgoltz** [comment]
Naming of the conformance classes could be improved (adapted to the [specification](http://www.geopackage.org/spec120/):
 * Extensions -> Extension Mechanism
 * Non-linear Geometries -> Non-Linear Geometry Types
 * RTree Index -> RTree Spatial Indexes
 * Webp -> Tiles Encoding WebP
 * CRS WKT -> WKT for Coordinate Reference Systems

**Comment by dstenger** [comment]
Proposal of https://github.com/opengeospatial/ets-gpkg12/issues/37#issuecomment-363413431 was moved to #41.

**Comment by dstenger** [comment]
TODOs:
* Update naming of conformance classes (https://github.com/opengeospatial/ets-gpkg12/issues/37#issuecomment-363430274).
* ```Attributes``` conformance class must be added to several files:
  * Update documentation.
  * Update tests run by Web Browser Interface. Enhance/Modify: #39 
  * Update default tests run by REST interface. Enhance/Modify: #31
  * Check configured basic conformance classes and conformance classes in testng.xml.

**Comment by lgoltz** [comment]
TODOs listed in https://github.com/opengeospatial/ets-gpkg12/issues/37#issuecomment-367002858 are implemented in #42:
 * Names of the CCs was updated as proposed in https://github.com/opengeospatial/ets-gpkg12/issues/37#issuecomment-363430274
 * Documentation was updated

> Check configured basic conformance classes and conformance classes in testng.xml.

Basic CC was not checked as this will be discussed in #41
