### ISSUE TITLE
How do we know the version tested against?

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg12#38]
I understand that this test so works for 1.0. 1.1 and 1.2.  How those the test know which version is testing?

**Comment by jyutzler** [comment]
The file reports its version. The test reads this version and tweaks the tests accordingly. 

* http://www.geopackage.org/spec120/#_file_format
* http://www.geopackage.org/spec110/#_file_format
* http://www.geopackage.org/spec101/#_file_format

**Comment by dstenger** [comment]
All questions are answered.
