### ISSUE TITLE
No unit tests for features, tiles, metadata test methods

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-gpkg12#4]
There are no unit tests for any test methods in these packages. While complete coverage may not be necessary, adding some would help to confirm that the implemented tests behave correctly when checking valid and invalid files.

**Comment by jyutzler** [comment]
There are no individual unit tests, but /src/test/java/org/opengis/cite/gpkg12/VerifyTestNGController.java calls the test suite for a hard-coded file. This mechanism can be expanded to include multiple test files (each with different test successes and failures). That should satisfy the desire for unit tests.

**Comment by jyutzler** [comment]
@rjmartell I did a significant amount of work in this area as part of #6. Please let me know if that work resolves this issue or if there is something else you are looking for. Strict unit testing is going to be virtually impossible with the way the tests are constructed (throwing exceptions on failures). There is no good automated way to check whether there is a test that fails a particular assertion.

**Comment by lgoltz** [comment]
@jyutzler Does the changes in #6 includes tests for features, tiles and metadata? In this case we can close the ticket.

**Comment by jyutzler** [comment]
Yep.
