### ISSUE TITLE
Test Suite Revision 0.4

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/ets-gpkg12#40]
Update the [GeoPackage version 1.2 Test Suite](http://cite.opengeospatial.org/te2/about/gpkg12/1.2/site/) to revision 0.4 with [the recent changes](https://github.com/opengeospatial/ets-gpkg12/compare/816929e...master?expand=1).  Also include pull request #39 so Attributes are tested.

Would like the updates pushed so GeoPackage test session results at http://cite.opengeospatial.org/te2 match master branch run test results.

**Comment by dstenger** [comment]
@bosborn Can you please create pull requests for all required changes?

An issue for the next release already exists (https://github.com/opengeospatial/te-releases/issues/214) and it will be created soon.

**Comment by bosborn** [comment]
Other than the open #39 , the other changes have already been pulled in (#32 , #33, #34).  Closing since this is tracked in te-releases.
