### ISSUE TITLE
Rename Tiled Gridded Elevation Data conformance class

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg12#46]
Remove 'Tiled Gridded Elevation Data' from the welcome page 
http://cite.opengeospatial.org/te2/about/gpkg12/1.2/site/

**Comment by dstenger** [comment]
According to https://github.com/opengeospatial/ets-gpkg12/pull/39 'Tiled Gridded Elevation Data' was kept in test suite.
What is the reason to remove it from welcome page?

@jyutzler 
Can you provide further details?

**Comment by dstenger** [comment]
'Tiled Gridded Elevation Data' is not approved by OGC TC, yet.

Tests can stay as they are right now, correct?

**Comment by jyutzler** [comment]
Given that `Tiled Gridded` ~Elevation~ `Coverage Data` has been adopted by OGC as an official GeoPackage extension, there is no reason to remove it from the welcome page anymore.

**Comment by bosborn** [comment]
It is a little confusing that `Tiled Gridded Elevation Data` is listed under `GeoPackage 1.2 Conformance Test Suite`.  GeoPackage 1.2 was approved on 2017-08-06 and Tiled Gridded Elevation Data on 2018-03-06.  Is `Tiled Gridded Elevation Data` being retroactively included in 1.2?  If so the tests need to be fixed [around here](https://github.com/opengeospatial/ets-gpkg12/blob/02ba0439a4d060c6cb036caa5d8225e18241e8e6/src/main/java/org/opengis/cite/gpkg12/extensions/elevation/ElevationTests.java#L307) to fix the extension name and definition.  Or is it included as part of a future 1.3 release?  In which case it should probably be removed or at least a note included?

**Comment by bosborn** [comment]
Sorry... it is `Tiled Gridded Coverage Data` that was recently approved.  I thought `Tiled Gridded Elevation Data` was pulled out last minute from being a 1.2 release.
http://geopackage.blogspot.com/2017/05/good-news-bad-news.html
http://www.opengeospatial.org/blog/2593

**Comment by jyutzler** [comment]
It looks like this is still generating some confusion. I suppose a blog post is in order.

**Comment by dstenger** [comment]
Current status of this issue: ```Tiled Gridded Elevation Data``` must be renamed to ```Tiled Gridded Coverage Data```.
This applies to TestNG configuration and documentation.
Issue was renamed.

**Comment by lgoltz** [comment]
Renamed conformance class, renamed package and test class and updated JavaDoc. PR: #48

JavaDoc of test `requiredSRSReferences` should be rechecked (I could not find a test case with ID `/opt/extensions/elevation/srs/required_references` in http://docs.opengeospatial.org/is/17-066r1/17-066r1.html)
