### ISSUE TITLE
ETS fails on poorly named contents tables

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/ets-gpkg12#52]
If someone naively names a content table something like `0`, most of the tests will break because `SELECT * FROM 0` is not valid SQL - the `0` needs to be escaped like `select * from '0'`. We need to sweep through the entire ETS to eliminate instances of unescaped table names.

**Comment by dstenger** [comment]
@jyutzler Do have example data to reproduce this behaviour?
@keshav-nangare Can you please create a fix for that?

**Comment by jyutzler** [comment]
@dstenger I do have an example. I also intend to produce a fix today. This fix will include the test case.

**Comment by dstenger** [comment]
Thank you!
@keshav-nangare Please wait for the fix of jyutzler.
