### ISSUE TITLE
Remove big files from repository and commit history

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#56]
Currently, there are two files > 50 MB in repository or commit history. GitHub throws are warning for those files [1] and thus they should be removed.

Affected files:
* haiti-vectors-split.gpkg
* imagery-0.gpkg

E.g. following tool can be used (tool must be tested first): https://rtyley.github.io/bfg-repo-cleaner/

[1] https://help.github.com/articles/conditions-for-large-files/

**Comment by jyutzler** [comment]
I don't want `haiti-vectors-split.gpkg` removed unless suitable replacements can be made. 60MB is not that big a deal in the grand scheme of things.

**Comment by dstenger** [comment]
Then, we can close this issue for now.

However, we should try to not add any files bigger than 50 MB.
