### ISSUE TITLE
RTreeIndex Tests Failure

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12#57]
The Requirement 77 tests, RTreeIndexTests fail consistently in the virtual table test and in the test for update 4. This is due to incorrect regular expression definitions:
- The virtual table test requires additional backslash characters prior to " in order to properly escape it.
- The virtual table test should account for additional spaces, or the use of a single quote rather than double quotes.
- For the virtual table test the following regular expression definition appears to work better: String.format("create\\s+virtual\\s+table\\s+\\\"?\\'?rtree_%s_%s\\'?\\\"?\\s+using\\s+rtree\\s*\\(\\s*id,\\s*minx,\\s*maxx,\\s*miny,\\s*maxy\\s*\\)", tableName, columnName);
- The test for update4 trigger is missing critical information within the regular expression. It should be looking for an ... AFTER UPDATE OF <c> ON TABLE ...   It is missing the "OF <c>" part.

**Comment by ajanett** [comment]
Additionally, the triggers using "INSERT OR REPLACE INTO" cannot be performed and these are also going to fail all of the time. The specification has some strange coloration on these statements possibly indicating a small "or", meaning these should be either INSERT INTO or REPLACE INTO. Typically one will see "INSERT INTO".

**Comment by dstenger** [comment]
Thank you for reporting.

@jyutzler Can you please do further investigations?

**Comment by jyutzler** [comment]
@ajanett 

Do you have a test file that demonstrates the problem? I have not seen this issue in any of the files that have been provided to this point.

I am also not clear if this a problem with the ETS or the standard. If the problem is in the standard, it needs to be posted to https://github.com/opengeospatial/geopackage.

**Comment by ajanett** [comment]
It appears the more recent revisions of the source have corrected the issues I was seeing so far.
