### ISSUE TITLE
Update documentation to explain how 1.1 and 1.0 are supported

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg12#58]
If 1.2 also supports 1.1 ad 1.0 we should update the documentation about how to execute a test for 1.1. and 1.0. Then we can remove the 1.0 ETS https://github.com/opengeospatial/ets-gpkg10/.

**Comment by jyutzler** [comment]
Once the 1.2 test is official, the 1.0 test should be removed. 

There are no documentation updates required to execute the test for 1.0/1.1. The test will automatically detect which version of GeoPackage is in effect in that file and adjust the tests accordingly. However, as per #54 the test does not currently report that file version in the output.

**Comment by lgoltz** [comment]
I've added a hint to the support of 1.1 and 1.0 at the README: https://github.com/opengeospatial/ets-gpkg12/commit/bf398ceea6aef4316f631487978cc5413ce36bf0

The information is already available on http://opengeospatial.github.io/ets-gpkg12/ as well as the entry point of the test (TEAM Engine Web GUI).
