### ISSUE TITLE
Feature Tests Being Skipped & Constraints Errors

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12#59]
With the current version "0.7-SNAPSHOT" of 0.6, all feature tests are being SKIPPED on all of the geopackages that I try it on.

For example, this geopackage:
https://portal.opengeospatial.org/files/?artifact_id=78819

Does not report any errors; it passes 19 core tests, 5 extension tests, 7 metadata tests and then skips everything else including all features tests.

I have attached two small geopackages, one that is like the one listed above, and other that 
[AGeoPackageForTest.zip](https://github.com/opengeospatial/ets-gpkg12/files/2028428/AGeoPackageForTest.zip)
that used to run the tests okay, and has a known rtree update trigger 4 error, but should otherwise be okay. It is also not running any feature tests - they are all skipped.
Additionally, it is now reporting some new issues:
Test method dataColumnConstraintsGlobMinMax:
[SQLITE_ERROR] SQL error or missing database (no such column
: minIsInclusive)
Test method dataColumnConstraintsInclusive:
[SQLITE_ERROR] SQL error or missing database (no such column
: minIsInclusive)
Test method dataColumnConstraintsTableDefinition:
The gpkg_data_column_constraints table does not have a valid
definition: missing column(s) expected [true] but found [false]
Test tns:Main Failed

Two questions:

Since these issues are in the 'extensions' area and this is an older geopackage that may not have extensions, why are these now issues?
How can I get the ETS for GeoPackage to run the feature tests?

**Comment by dstenger** [comment]
Thank you for reporting.

I executed the on beta web site [1] as the installed revision of the test suite is currently equal to 0.7-SNAPSHOT.

**feature tests**

For both example files all feature tests are executed. How did you set up your TEAM Engine instance?

**schema tests**

@jyutzler Can you explain why schema tests are executed for those files?

[1] http://cite.opengeospatial.org/te2/

**Comment by ajanett** [comment]
I am using TEAM Engine 5.2 in both a standalone mode and with Tomcat 7.0.X.  Perhaps there is a dependency on TEAM Engine 5.3?

**Comment by ajanett** [comment]
Updated to current TEAM Engine and now features tests are being run.  In comparing the results from yesterday to today, the code within the current ets-gpkg12 (0.7 SNAPSHOT) and version 0.6 of Features; something within SetUp method for features is apparently incompatible with TEAM Engine 5.2.  The "Conformance class" for features fails and then all tests are disabled.

**Comment by dstenger** [comment]
No, the test suite should work with both, TEAM Engine 5.2 and 5.3. There is no (new) dependency to any TEAM Engine functionalities.

However, good to hear that it is working now.
