### ISSUE TITLE
The spatial issue revisited

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12#60]
The GeoPackage Tests that may need to delve into the geometry blob include those for requirements 12-128r14 19, 20, 32, 33, 67, 78 and also NSG Requirement 19B. For the most part, these include evaluation of geometry spatial reference, geometry type, envelope min/max. Requirement 66, then goes even more in-depth into the entire WKB.

The issue discussed before:
Is there a need for the spatialite extensions or a subset of these extensions to be available within the ETS GeoPackage?

Maybe for the WKB decoding (requirement #66), but there are other issues with #66 and I'll post that in a moment. 

It isn't that complicated to get the spatial reference, envelope, and geometry type from the geometry BLOB and in order to test these with ANY kind of performance, we need to crack open the geometry BLOB once per feature instance and make all tests on it. Therefore, SQL extensions are not going to provide the necessary performance.  The only caveat that I know is that we need to assume the envelope min/max is representative of the feature min/max.

I've got an implementation of these tests ready to insert into this GeoPackage test tool, but am awaiting a fix on another issue to finalize my testing of these extensions.

**Comment by dstenger** [comment]
Thank you! You are welcome to create a pull request as soon as you are finished with testing.

**Comment by jyutzler** [comment]
Are we satisfied with #70 (which includes #62)?
