### ISSUE TITLE
Failure due to space in filename

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12#64]
The GeoPackage specification has no limitations on characters in filenames and does not state that spaces are not allowed. The only requirement is 'A GeoPackage SHALL have the  file extension name ".gpkg".'.  In the case that a geopackage has the .gpkg extension, but a space in the name, the ETS fails with an immediate Fatal Error in calling an extension function which eventually tells us there is an "illegal character in path'. Removal of the space from the file name corrects the issue. However, the problem here is that the test code should not HARD fail on such an item. If spaces are a problem and not to be allowed, the test code should report this as an issue; and the specification should also include the requirements to support this if necessary.

**Comment by jyutzler** [comment]
Now that the TC is behind me, I'm looking at a sprint on the ETS. I will take a look at this and other ETS issues.

**Comment by jyutzler** [comment]
This must be a TEAM engine problem. PR #65 does not duplicate the issue. I am unassigning myself.

**Comment by dstenger** [comment]
@keshav-nangare Can you please do further investigation and create a TEAM Engine issue in case it is related to it?

**Comment by keshavnangare** [comment]
Fixed with this commit: 11c912d0a3dd370f80ec4ac0b3d77d4f8fcbea9d [PR: #64]

**Comment by dstenger** [comment]
Fix did not work and merged branch was reverted: https://github.com/opengeospatial/ets-gpkg12/pull/66#issuecomment-398817279

**Comment by keshavnangare** [comment]
Fixed this issue with commit: ed41f4c

Tested the fix with following data:
1. [emp ty.gpkg](https://github.com/opengeospatial/ets-gpkg12/raw/master/src/test/resources/gpkg/emp%20ty.gpkg)

2. [bluemarble.gpkg](https://github.com/opengeospatial/ets-gpkg12/raw/master/src/test/resources/gpkg/bluemarble.gpkg)
