### ISSUE TITLE
Test setupVersion is executed multiple times

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gpkg12#75]
once for each class extending CommonFixture as the test if implemented there.

The test should be moved to a separate class.

**Comment by jyutzler** [comment]
Fixing as part of #77

**Comment by dstenger** [comment]
#77 does not change the behaviour regarding this issue.

Test setupVersion is still executed in each conformance class.

In addition,
test ```feature Geometry Columns Data Values Geometry Type``` is executed in CCs ```Features ``` and ```Non-Linear Geometry Types ``` (2 times in total) and
test ```image Format``` is executed in CCs ```Tiles```, ```Tiles Encoding WebP``` and ```Tiled Gridded Coverage Data``` (3 times in total).

Also see #76.

**Comment by dstenger** [comment]
# Functional test

Test
```setupVersion``` renamed to ```geopackageVersion```
is just executed once.

Though, tests ```feature Geometry Columns Data Values Geometry Type``` and ```image Format``` are still executed multiple times.

**Comment by dstenger** [comment]
Behaviour was documented in #82.
