### ISSUE TITLE
Several tests are executed multiple times

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#76]
I recognized that several tests are executed multiple times.

All tests in ```Tiles``` conformance class are also executed in
* ```Tiled Gridded Coverage Data```
* ```Tiles Encoding WebP```

All tests in ```Features``` conformance class are also executed in
* ```Non-Linear Geometry Types```

The reason for this behaviour is that classes ```WebPTests```and ```TiledGriddedCoverageTests``` extend ```TilesTests``` and class ```NonlinearTests``` extends ```FeaturesTests```.

Is this behaviour on purpose?
If this is not the case, I propose to remove multiple test executions.

**Comment by jyutzler** [comment]
This can be accomplished by adding some abstract classes. See #77.

* [x] ```Tiled Gridded Coverage Data```
* [x] ```Tiles Encoding WebP```
* [x] ```Non-Linear Geometry Types```

**Comment by dstenger** [comment]
PR #77 solves the problem. A functional test was executed.
