### ISSUE TITLE
Tests "feature Geometry Columns Data Values Geometry Type" and "image Format" are executed multiple times

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#82]
Test ```feature Geometry Columns Data Values Geometry Type``` is executed in CCs ```Features ``` and ```Non-Linear Geometry Types ``` (2 times in total) and
test ```image Format``` is executed in CCs ```Tiles```, ```Tiles Encoding WebP``` and ```Tiled Gridded Coverage Data``` (3 times in total).

Also see #75.

**Comment by lgoltz** [comment]
The tests have the same name but tests different requirements.
