### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gpkg12#89]
https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

**Comment by keshavnangare** [comment]
Fixed with this commit: b92fb08893bea5f8cd29f53709301c66f7ed786d & PR: #92.

The test suite is getting skipped when tested with these resources(from reference implementation page): https://demo.luciad.com/GeoPackageData/

So the changes are tested with the local .gpkg file.

**Comment by dstenger** [comment]
`mvn clean install -Pintegration-tests` now runs successful.
