### ISSUE TITLE
Add tests for Related Tables Extension

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/ets-gpkg12#90]
Now that the [Related Tables Extension](http://docs.opengeospatial.org/is/18-000/18-000.html) has been adopted by OGC, the ETS needs to be updated to include tests for it.

**Comment by jyutzler** [comment]
This is currently assigned to me, but I have provided a pull request that fixes the issue. What is the next step?

**Comment by dstenger** [comment]
As you are the test lead, it is fine if you merge the pull request. If you think it is better that the rest of the CITE team reviews it, please inform us.
