### ISSUE TITLE
Typo in org.opengis.cite.gpkg12.extensions.crswkt.CRSWKT.tableDefinition()

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-gpkg12#95]
There is a recurring typo in Typo in org.opengis.cite.gpkg12.extensions.crswkt.CRSWKT.tableDefinition(): the constructed error messages contain "definition_16_063" instead of "definition_12_063". These error messages are shown in the OGC validator:

![image](https://user-images.githubusercontent.com/11427611/72261523-4a7adb00-3615-11ea-96e4-a4cb4526f0ad.png)

(this particular error message is from an older test, before https://github.com/opengeospatial/geopackage/issues/423 was resolved, but the typo is present for other checks are well)

**Comment by dstenger** [comment]
Thank you for providing the pull request.
