### ISSUE TITLE
Failed tests with disabled conformance classes.

### ISSUE THREAD

**Issue by ollewis** [opengeospatial/ets-gpkg12#98]
The `validateClassEnabled` test methods are failing for every conformance class not being implemented even when the conformance class is not specified within the ics test run argument. 

For example, if a GeoPackage only implements the Features conformance class, running the ETS with the following test run argument: `<entry key="ics">Core,Features</entry>`, will result in `validateClassEnabled` failing within every class except for Core and Features. The failure message is:
> "<![CDATA[Conformance class _className_ is disabled. expected [true] but found [false]]]>" 

Is this behaviour by design? I would have expected all tests to be skipped within a conformance class if that class was not specified to be supported by the GeoPackage. 

Furthermore, if the ETS is run without the ics test run argument then I would have expected the `validateClassEnabled` tests to fail for each conformance class not specified. Instead, these tests are passing while another test will fail (the specific test varies based on the class). Regardless of the class, the failure message is: 

> "<![CDATA[Conformance class _className_ is not in use. expected [true] but found [false]]]>"

This behaviour is also not what I would have expected.

I've attached both testng-results.xml files. Each file is generated from running the ETS on the same GeoPackage.

- `ics_CoreFeatures.xml` is the testng-results.xml generated from specifying "Core,Features" within the ics entry.
- `ics_Empty.xml` is the testng-results.xml generated from excluding the ics as a test run argument.

[testng-results.zip](https://github.com/opengeospatial/ets-gpkg12/files/4299681/testng-results.zip)

**Comment by dstenger** [comment]
Thank you for reporting.
@keshav-nangare Can you please analyze the reported behavior?

**Comment by keshavnangare** [comment]
The current behavior of the ets is as follows:
- If ICS parameter is not set then it will execute all the conformance classes by default.
- If ICS parameter is set then it will execute only that conformance classes and skipping other classes.

@dstenger 
I think this behavior could be expected as it's skipping the conformance classes, not impacting the whole test result. What is your thought on this?


Regarding the below error message:
> "<![CDATA[Conformance class className is not in use. expected [true] but found [false]]]>"

For example below is the snippet which is throwing the above error message so I am not sure whether the assertion is correct or not. What is the expected error message if the attribute is null?
https://github.com/opengeospatial/ets-gpkg12/blob/eeb9663e164705ed1675bbca586cd9d23af00f4f/src/main/java/org/opengis/cite/gpkg12/attributes/AttributeTests.java#L51


Here is the one session I ran on the local machine and we can see the result
I have sent **Core, Features** as ICS parameter and the test is passing for them skipping other classes.
![Result](https://user-images.githubusercontent.com/14732650/76408028-50d9c900-63b2-11ea-9e25-f464e245e243.png)

**Comment by dstenger** [comment]
The overall result of `ics_CoreFeatures.xml` looks fine: `<testng-results skipped="65" failed="1" total="97" passed="31">`.

@ollewis Does this answer your question? Are there any open questions?

@keshav-nangare Can you please improve the error message?

**Comment by ollewis** [comment]
@dstenger The main reason I'm questioning the intended behaviour is because I find that having a test fail for a reason that is unrelated to a GeoPackage not conforming with the specification, or the data within the GeoPackage being invalid, is not intuitive. 

My thinking is that a GeoPackage may be 100% valid but if not all conformance classes were implemented there will still be failed tests. Another scenario, demonstrated by `ics_CoreFeatures.xml`, is that there may be one failed test due to a geometry error, and 8 others due to a conformance class not being implemented; however, the `testng-results` element only shows that 1 test failed. In this case, there is no way for me to be certain as to which test was counted as the failure.

My own opinion is that this test should be marked as something other than "FAIL", perhaps a warning instead. Or, maybe there could be another element or attribute to allow differentiation between a failed test that is counted in `testng-results`, and one that is not.

Thank you @dstenger and @keshav-nangare for spending the time to address my concern. I appreciate it!

**Comment by dstenger** [comment]
Thank you for the input.
However, the method is not marked as a test (`@Test`) but with `@BeforeClass`. This means that TestNG does not consider this method as a real test but as a pre-check. Thus, the implementation is fine in consideration of logic of TestNG framework.

**Comment by keshavnangare** [comment]
@dstenger 

I have improved the message in AttributTest.java with #101  PR. I found it is present in other conformance classes methods.
Should I update it in all tests?

**Comment by dstenger** [comment]
Yes, please update all tests.

**Comment by ollewis** [comment]
That makes sense to me now. Thank you for the help!

**Comment by keshavnangare** [comment]
I have updated the error message in the remaining files.
