### ISSUE TITLE
Req. 78 is still being enforced

### ISSUE THREAD

**Issue by ollewis** [opengeospatial/ets-gpkg12#99]
Requirement 78 seems to be deprecated as of [OGC 12-128r14](http://www.geopackage.org/spec120/index.html#extension_rtree); however, the most recent version of the ETS is still enforcing this requirement. 

If it helps, [here is the issue](https://github.com/opengeospatial/geopackage/issues/341) that I believe should of addressed this change.

I've also linked the portion of code that is currently testing requirement 78. 

https://github.com/opengeospatial/ets-gpkg12/blob/eeb9663e164705ed1675bbca586cd9d23af00f4f/src/main/java/org/opengis/cite/gpkg12/features/FeaturesTests.java#L968-L1041

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by keshavnangare** [comment]
@dstenger 

I have referred documentation and found that requirement 78 is deprecated but it is still used in the test. Should I remove it?

**Comment by jyutzler** [comment]
Yes.

**Comment by keshavnangare** [comment]
Fixed with #100 PR.

**Comment by jratike80** [comment]
The change into the standard was introduced in 
https://github.com/opengeospatial/geopackage/commit/f2482abcc42a96b87dfd4970f9a1a08f493fc9b5#diff-c1aba1c1e37494be8225c64af76beb82

Commit includes a note about the RTree envelope vs. feature envelope test.

> [NOTE]
> The minimum bounding indices created within the RTree Extension for GeoPackage should reflect the appropriate bounding area for the indexed feature. However, due to varying precision implementations, it is not practical to assert this practice through a requirement or test. 
>
